name: final_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.4.0
  path_provider: ^2.0.11
  path: ^1.9.1
  cupertino_icons: ^1.0.8
  encrypted_shared_preferences: ^3.0.1
  provider: ^6.0.5
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  floor_generator: ^1.4.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
